version: '3'
services:
  postgres:
    container_name: crystal-postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=tibia
      - POSTGRES_PASSWORD=clicky
      - POSTGRES_DB=crystal

  django:
    container_name: crystal-django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=crystal-postgres
      - DB_NAME=crystal
      - DB_USER=tibia
      - DB_PASSWORD=clicky
    depends_on:
      - postgres
