# Generated by Django 4.2.1 on 2023-05-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vocation', models.CharField(max_length=255)),
                ('x_max', models.FloatField()),
                ('y_max', models.IntegerField()),
                ('x_min', models.FloatField()),
                ('y_min', models.IntegerField()),
                ('target_cap', models.IntegerField()),
            ],
        ),
    ]
